cmd/go-sbot/main.go
Fix use of AllKeyPair return value.
Fixes #33
=> Fix go-sbot build failure

README.md
Help user find and report issues in README.
=> Add issues link in README

cmd/go-sbot/main.go
Copy the pattern from docker's cli to log and return errors without panicing.
=> go-sbot: Panic less in main()

.github/workflows/go.yml, .travis.yml, internal/statematrix/store.go
This should fix #78 by writing to a new file and renaming once it's written, making the operation more atomic.
ps: Got these patches out-of-band. Making this PR for visibility.
=> fix ebt eof

ebt.go, go.mod, go.sum, graph/builder.go, internal/statematrix/store.go, internal/statematrix/store_test.go, multilogs/combined.go, network/new.go, network/tunnel_connect.go, plugins/blobs/handler_test.go, plugins/ebt/handler.go, plugins/ebt/plug.go, plugins/ebt/session.go, plugins/gossip/feed_manager.go, plugins/test/setup.go, private/groups_test.go, sbot/feeds_gabby_test.go, sbot/feeds_live2_test.go, sbot/feeds_live_test.go, sbot/feeds_reconnect_test.go, sbot/feeds_test.go, sbot/manifest.go, sbot/new.go, sbot/replicate.go, tests/ebt_test.go, tests/feeds_test.go, tests/format_ggrove_test.go
updates #75 point 3. The circular dependency is gone!
=> Untangle statemat from replication

README.md
Just an idea, feel free to do whatever with this patch :)
=> Tweak the logo on the readme a bit

README.md
=> Set height on image

cmd/sbotcli/aliases.go, cmd/sbotcli/blobs.go, cmd/sbotcli/friends.go, cmd/sbotcli/main.go, cmd/sbotcli/publish.go, cmd/sbotcli/simple_test.go, cmd/sbotcli/streams.go, go.mod, go.sum, message/drains.go, message/verifier.go, plugins/ebt/handler.go, plugins/ebt/plug.go, plugins/gossip/fetch.go, plugins/gossip/handler.go, plugins/gossip/plugin.go, sbot/manifest.go, sbot/new.go, sbot/null.go
=> misc cleanup

go.mod, go.sum, graph/builder.go, graph/builder_indexing.go, graph/builder_test.go, graph/metafeeds_test.go, sbot/metafeed.go, sbot/metafeed_test.go, sbot/new.go
=> test metafeed announcement & resulting hops

plugins/gossip/handler.go, sbot/replicate_negotiation.go
StartLegacyFetching accepts a parameter withLive to control whether live
streaming is used. At the same time field enableLiveStreaming is used to
control the behaviour in the HandleConnect method.
On top of all of that replicateNegotiator specifies a separate flag for
this behaviour. This flag is never set. Instead of this flag the flag
from LegacyGossip should be used.
To address all of this I removed the flag from the method completely and
now the implementation relies on the field in LegacyGossip. I completely
removed the flag from replicationNegotiator as it is not set. I also
removed the other flag disableEbt which is never used and just adds to
the confusion. Disabling ebts is handled differently by the code.
=> Fix incorrect field reuse in LegacyGossip

README.md, docs/faq.md
Closes https://github.com/ssbc/go-ssb/issues/80
=> docs: start faq

Makefile, cmd/gossb-migrate-mf/migrate/migrate_test.go, graph/builder_test.go, graph/people_test.go, message/legacy/metafeed_announce_test.go, message/legacy/verify_invalid_test.go, multilogs/combined_test.go, plugins/private/handler.go, private/manager_groups.go, query/subsetquery_test.go, sbot/groups_test.go, sbot/metafeed_test.go, sbot/null_feed_test.go, sbot/persistence_test.go, sbot/unipub_test.go, tests/blocking_test.go
Sorry @staltz I realise it would be much easier to review fixes in a single PR which has a green build :upside_down_face:
=> Fix test suite

README.md
[Rendered](https://github.com/decentral1se/ssb/blob/e1a73a1324a84a47a1d053e497ae5aee3b92a8dc/README.md)
=> README.md formatting / contacts

blobstore.go, blobstore/store.go, blobstore/wants.go, internal/broadcasts/blobstore.go
Backporting https://github.com/planetary-social/ssb/commit/47d4e754b76157fe3eb0e4dd3e4cc3c9ab9dd5e9 & https://github.com/planetary-social/ssb/commit/8347cfac9d43396ccb6d3c198b8eaccd09cc946c from https://github.com/planetary-social/ssb/commits/fork from the good work of @boreq :100: No tests but Planetary are running the code so let's goo foorrr ittt :crossed_fingers:
=> fix: blob deadlock backport

blobstore/wants.go
Seems like a good guess to backport https://github.com/planetary-social/ssb/commit/ba78c6bf2aa98d4075ce83479deab8cc380a5029
@boreq
=> fix: WantManager "deadlock" backport

go.mod, go.sum
@staltz 
See https://github.com/ssbc/go-ssb/pull/180.
=> chore: update go-muxrpc (arm arch fixes)

docs/faq.md
Typing is hard :sweat_smile: @staltz @mycognosist
=> docs: typos

go.mod, go.sum
Follows https://github.com/ssbc/go-muxrpc/issues/17
=> chore: upgrade go-muxrpc

client/client.go, client/client_test.go, message/requests.go
Closes https://github.com/ssbc/go-ssb/issues/203.
=> feat: invite create exposed on client API

cmd/go-sbot/config.go, cmd/go-sbot/config_test.go, cmd/go-sbot/main.go
Still have to run tests but had an issue on my local system, likely due to conflicts introduced from newer go versions ([context](https://www.reddit.com/r/golang/comments/rn25ov/encountering_gobuild_comment_without_build/))
=> Expand repo path according to expectations

docs/faq.md
Closes https://github.com/ssbc/go-ssb/issues/87.
[Rendered](https://github.com/decentral1se/ssb/blob/52bcf9331142d4e7dc26a4670760e59d6cf10c3e/docs/faq.md).
=> docs: legacy messages / replication [ci skip]

docs/faq.md
Realised this isn't that obvious after some chats with folks. Documenting here might help.
Related to https://github.com/ssbc/go-ssb/issues/66.
[Rendered](https://github.com/decentral1se/ssb/blob/035ac9bfd70e7d750d071c357c2b96f5de02954d/docs/faq.md).
=> [docs]: outgoing conn handler [ci skip]

cmd/sbotcli/aliases.go, cmd/sbotcli/blobs.go, cmd/sbotcli/friends.go, cmd/sbotcli/main.go, cmd/sbotcli/publish.go, cmd/sbotcli/streams.go
Related to https://github.com/ssbc/go-ssb/issues/217 & https://github.com/ssbc/go-ssb/issues/211.
=> docs: further sbotcli documentation [ci skip]

client/client.go, client/client_test.go, message/requests.go
Closes https://github.com/ssbc/go-ssb/issues/244. Exposed it on the Go client bindings while I'm there.
=> test: add test for friends.blocks MUXRPC call

.gitignore, cmd/go-sbot/config.go, cmd/go-sbot/config_test.go, cmd/go-sbot/default-config.toml, cmd/go-sbot/main.go, docs/config.md, go.mod, go.sum
Following the wisdom of https://github.com/ssbc/go-ssb/issues/223#issuecomment-1326630237.
@cblgh do you have cycles for a quick review? Np if not.
[Rendered docs](https://github.com/ssbc/go-ssb/blob/4fd876496916f9ce1994826f50e59738eca793fd/docs/config.md).
=> feat: generate default config.toml

graph/builder_test.go
See https://github.com/ssbc/go-ssb/issues/237. Ran it ~ 90 times, no failures.
=> test: TestBadger works again

cmd/go-sbot/crashrecovery_test.go
As I continue to lazily find the tests which magically work again :upside_down_face:  100 times not failing... https://github.com/ssbc/go-ssb/issues/237.
=> test: TestDontStartTwiceOnTheSameRepo is back

message/legacy/signature.go, message/legacy/verify_invalid_test.go
Fixes #284 
Simplified version of #285
=> Fix TestInvalidFuzzed (Simplified)

plugins/legacyinvites/master.go, tests/invite_legacy_test.go
See https://github.com/ssbc/go-ssb/issues/237.
=> Fix TestLegacyInviteJSAccept

tests/local_fork_test.go
Ran over 500 times with zero failures.
Fixes #261
=> Fix TestStartup

graph/builder.go, graph/builder_indexing.go, graph/builder_test.go, graph/people_test.go, multilogs/userfeeds.go
Fixes #274 
Ran successfully over 1000 times.  Then I went back, cleaned up the extra logging code I used to trace it, and simplified it and ran it a few more times successfully.
That was a massive pain to track down.
=> Fix TestPeople

go.mod, go.sum, internal/transform/qrymap.go, message/legacy/stored.go, plugins/tangles/plugin.go, private/manager.go, private/unboxlog.go
See https://github.com/ssbc/go-ssb/issues/324.
=> Use Millisecs from go-ssb-refs

cmd/go-sbot/config.go, cmd/go-sbot/config_test.go, cmd/go-sbot/default-config.toml, cmd/sbotcli/aliases.go, cmd/sbotcli/config.go, cmd/sbotcli/config_test.go, cmd/sbotcli/main.go, docs/config.md, internal/config-reader/config.go
See #151 
Not quite done yet, but making progress.
=> Allow for configuration of both go-sbot and sbotcli
