message/encode.go
message/replace.go

This fixes two identified cases. There might be more.
1) fix \f encoding
Somehow this one wasn't captured by %q in encode.go
There might be a better place for unicodeEscapeSome()
2) keep original string of floats
Reproducing the exact behavior of v8' JSONification of floats is still
troubling.

Fix Message Verification (updates #5)

---

graph/builder.go
graph/people_test.go

There were two `return`s in the follow-graph builder that aborted the generation of the graph prematurely. This adds tests for those cases and fixes the code by `continue`ing as it was intended in the first place... :see_no_evil:

Fix graph build

---

keys.go
keys_test.go

Save key file with secret key permissions like in ssh, and require secret key permissions like in ssh.

Secret key file permissions

---

README.md

Use git clone make installation instructions more resilient.

README: use git clone for installation

---

blobstore.go
blobstore/store.go
refs.go
sbot/new.go
sbot/options.go

This extracts `BlobRef.IsValid()` from the fs-based store and also adds an option to sbot (`WithBlobStore`) so that implementations can be switched out.

Add blobstore option to sbot

---

README.md
keys.go
keys_default.go
keys_windows.go
repo/badger_default.go
repo/badger_ios.go

use `go build -tags nommio` to fix #51 
cc @freight-stack i think you needed this for your Pi
cc @pietgeursen i guess the gobot for sunrise-social could use this update, too.
this uses the '// +build ...'  quasi-macro at compile-time
to decide which perms to check the secret file for.
closes #54
updates #52
cc @soapdog could you try this?

various fixes

---

keys_darwin.go
keys_default.go

Bootstrapping from secret generated by the latest version of Patchwork causes an error:
- https://github.com/cryptoscope/ssb/issues/52#issuecomment-644621296
Having OSX-specific `keys.SecretPerms` fixes the problem.

Fix expected permissions of the secret file on OSX

---

cmd/sbotcli/main.go
multilogs/combined.go
multilogs/membership_index.go
network/new.go
plugins/groups/handler.go
plugins/groups/is.go
plugins/rawread/logt.go
private/groups_test.go
repo/timestamp_sorter.go
sbot/new.go

This takes advantage of set operation on roaring bitmaps that we keep per author, per message type and per _decryptable by us_. This way we can construct the set of _whose messages of this author are box2 but not yet readable_ and just reindex those.
The first attempt showed a problem with the bitmap indexes where the order is not kept as (previous) messages are added. ie first message is A and the set is [A]. As a message B which is before A is discovered (decrypted) it get's added to the same set but since its receive sequence is smaller then A the set looks like [B, A] and reading the 2nd message from that set will result in processing A twice.
As a workaround I'm loading an older _badger multilog_ index which keeps the order (the set is [A,B]). A better approach would be to use the …

private groups reindex

---

README.md

The Scuttlebutt feed ID was missing the last digit (9).
BTW: I am `@+pY9goiTAmglEUMx+eXx2MpRExAY73C3RVGPy7QxrqQ=.ed25519`.

Fix keks' feed ID in README

---

docs/quick-start.md

@cryptix here is a quick-start guide as promised. 
I put it in docs/quick-start.md but I'm not sure where you would want this to live? 
alternatively, if you want to avoid docs duplication, we could just add a section to the main readme about invites and how to test that go-sbot is working? 
I basically just wrote a guide as though I was the intended audience, with just the getting started stuff I would have needed without the other stuff.

Add quick start for go-sbot documentation

---

README.md

Added a subsection to the first section of the readme with a link to the dev docs at https://dev.scuttlebutt.nz/#/golang/

Add dev docs (treasure map link) section to  readme

---

keys.go
keys_default.go
keys_test.go

This PR comes in two:
1. A fix for the default permissions, making them stricter 
2. An experimental tweak to the permissions behaviour, where go-sbot tries to set any incorrect permissions to what it expects (rather than error out and force users to deal with it)
@cryptix I'm okay with if you wanna throw out part 2, but I wanted to have a try at it since I think it's a bit nicer for users :)
Related to and fixes #131

Set stricter permissions as default, try to chmod incorrect permissions automatically

---

client/replicate_test.go

While Publish returned a ref in the past it now returns a message.
Further fixes are still needed to make the pipeline green again.

Fix a compilation error in tests

---

Makefile

This PR is a small QoL addition to making go-ssb releases. It changes the `Makefile` to use an OS/ISA matrix that allows it to build for multiple operating systems and multiple architectures. There is also a special case to build universal binaries for macOS that only works from a mac.

OS/ISA matrix for Makefile

---

sbot/get.go

This was found by running go vet:
sbot/get.go:15:9: Get passes lock by value: go.cryptoscope.co/ssb/sbot.Sbot contains go.cryptoscope.co/ssb/internal/multicloser.MultiCloser contains sync.Mutex

Fix passing lock by value

---

repo/badger_ios.go

Those options were removed in dgraph-io/badger@e3a0d29. To keep the
memory footprint low on mobile devices ValueLogFileSize was set to 2MB.
Preliminary testing shows that this configuration correctly works on
mobile devices, namely iPhones. This change should then be at least
partially compatibile with the previous settings.

Switch away from FileIO as Badger's value loading mode

---

.gitignore

I run `go build ./cmd/go-sbot` as I run the editor from the repo root also.
This PR ignores those binaries also.

fix: ignore binaries when built in root

---

cmd/go-sbot/main.go

If `~/.go-ssb` or `-repo <PATH>` doesn't exist, create it. 
Uses `0700` as default perms for more secure perms.
Closes https://github.com/ssbc/go-ssb/issues/144.
Before this patch:
```
❯ ./go-sbot -repo .foo
level=info t=58.149µs event="read config" msg="no config detected" path=.foo/config.toml
t=662.008µs event=panic location=main-panic panicLog=panics/main-panic3547787861 err="open .foo/running-config.json: no such file or directory"
```
After this patch:
```
❯ ./go-sbot -repo .foo   
level=info t=237.161µs event="read config" msg="no config detected" path=.foo/config.toml
level=info t=601.684µs event="write running-config.json" msg="active config and env vars have been persisted" path=.foo/running-config.json
level=info t=661.383µs event="set repo" …
```

fix: create configPath if it doesn't exist

---

README.md
docs/quick-start.md

addresses Issue #158 
Notes: this mucks with some of the badges, which I think is appropriate, but i don't know that either the old version or the new version are necessarily good, so while I don't think this necessarily makes anything worse because the badges were pointing at old places anyway, I think the badges section should be re-evaluated
I have also deleted the travis CI link because it wasn't working anyway (old or changed form). I'll leave it to someone more familiar with travis these days to fix that.
Also, there's a LOT of `go.cryptoscope.co` both in code, and URLs, which may be fine but i figure at least the urls referenced in the README should be called out for reconsideration.

updated urls in readme and quickstart

---

.github/workflows/go.yml
README.md
message/publish_test.go
sbot/names_test.go
sbot/null_feed_test.go
tests/invite_legacy_test.go

Closes https://github.com/ssbc/go-ssb/issues/168
Build times should be ~6 mins vs 20+ mins in general when caching is in place.
There are still a lot of flaky tests so I'm just skipping them for now... will come back for them...
@staltz

Wire up caching on CI

---

README.md
cmd/go-sbot/config.go
cmd/go-sbot/config_test.go
cmd/go-sbot/main.go
docs/config.md
docs/faq.md
plugins/gossip/fetch.go
plugins/gossip/handler.go
plugins/gossip/plugin.go
repo/badger_default.go
repo/badger_ios.go
repo/badger_lite.go
sbot/new.go
sbot/options.go

For https://github.com/ssbc/go-ssb/issues/124 testing @mycognosist @interfect @luandro @vielmetti @ahdinosaur  :construction: 
Now that https://github.com/ssbc/go-ssb/pull/176 landed, the new BadgerDB data store is incompatible with previous versions afaiu. So, please back up your `~/.ssb-go` before testing if you still have one! Best start from a fresh `~/.ssb-go` / keypair while testing, I guess. There may be some way to migrate it forward, can take a look if you need that.
There could be more to tweak in the new BadgerDB configuration, we can consult https://github.com/dgraph-io/badger/blob/main/docs/content/get-started/index.md#memory-usage & https://pkg.go.dev/github.com/dgraph-io/badger/v3#Options.
This PR adds a new lightweight BadgerDB config that @mplorentz / @boreq @ Planetary …

feat: badger lite & limited replication backports

---

go.mod
go.sum

Mucking around with fixes for https://github.com/ssbc/go-ssb/issues/183. Supercedes https://github.com/ssbc/go-ssb/pull/186.

chore: upgrade margaret to latest

---

README.md
docs/faq.md

@mycognosist 
Think this is basically everything I know at this point.
- [`README.md` rendered](https://github.com/decentral1se/ssb/blob/352ad46e7619ecb7bb8e18f073efccf9ef9a3c7b/README.md)
- [`FAQ.md` rendered](https://github.com/decentral1se/ssb/blob/352ad46e7619ecb7bb8e18f073efccf9ef9a3c7b/docs/faq.md)
Added `[ci skip]` to avoid wasting CI build cycles on this one.

docs: moar faq & updates

---

cmd/sbotcli/streams.go

Got renamed in 8b49ff543a2ef7a15a79050f21568eb6b847ce80 but `sbotcli` didn't get updated.
So you can do `./sbotcli replies "%bVCZHYhsQEdz/TNXPXuhHhbzL58ILktaiAVv4aQdjso=.sha256"` and get all the relevant messages connected with that root. This isn't quite "backlinks" level functionality afaiu but a client could make use of this output to sort by the various fields in the resulting JSON.
If I can further grok the cryptix notes below, another step would be exposing the `root: ...` indices... 
Deffo need this functionality for making client experiments...
`%tYzpHO2irGnJEKMomIoVFNzAI8FCAk+ILs07ufA6iDE=.sha256`
@mycognosist

fix: replies muxrpc call

---

Makefile

@mycognosist Partial revert of 1836e4a5f40f7c534da2d2c0c873faa8ba04a470. Follows https://github.com/ssbc/go-ssb/issues/192#issuecomment-1302106920.

ci: fail sooner if hanging

---

cmd/gossb-migrate-mf/migrate/migration.go
cmd/sbotcli/main.go
cmd/sbotcli/simple_test.go
invite/legacy.go
plugins/legacyinvites/master.go
tests/invite_legacy_test.go

@staltz @mycognosist 
Closes https://github.com/ssbc/go-ssb/issues/181
- fixes the parsing of `--uses n` on the `invite create ...` on `sbotcli`
- adds `invite accept <invite> <feed-id>` to `sbotcli`

fix: invite --uses parsing & invite accept

---

.gitignore
.goreleaser.yml

See https://github.com/ssbc/go-ssb/issues/188. Experimental binaries built with this config are available on:
> https://vvvvvvaria.org/~decentral1se/ssb/go-ssb
Will be doing some testing with them before merging this. Let me know if you're testing also :heart: 
Generated with `goreleaser release --snapshot`.

build: wire up goreleaser config

---

README.md
docs/config.md
docs/quick-start.md

Build process documentation assumes the `git clone` will clone into a directory called "ssb".  It actually defaults to "go-ssb".  This fixes the documentation.

Fix directories for build process

---

docs/faq.md

Closes https://github.com/ssbc/go-ssb/issues/62.
[Rendered](https://github.com/decentral1se/ssb/blob/35f211929dac7432eb203747af2edf461d61da8a/docs/faq.md).

docs: sbotc docs [ci skip]

---

README.md
docs/faq.md

Related to https://github.com/ssbc/go-ssb/issues/229.

docs: more issues to faq [ci skip]

---

network/tunnel_connect.go
sbot/manifest.go

Don't know if this is the correct way to do this, but this adds support for the `tunnel.ping` RPC from the https://github.com/ssbc/ssb-tunnel package that `ssb-browser-demo` uses.

Add support for tunnel.ping RPC

---

cmd/sbotcli/publish.go

Another wave of improvements to `Usage` and `ArgsUsage`, this time in `cmd/sbotcli/publish.go`.

Improve sbotcli docs for publish module

---

sbot/manifest.go

Closes https://github.com/ssbc/go-ssb/issues/241.

fix: expose friends.blocks on manifest

---

cmd/sbotcli/blobs.go
cmd/sbotcli/friends.go
cmd/sbotcli/main.go
cmd/sbotcli/publish.go
cmd/sbotcli/streams.go

Going through `sbotcli` and adding an example (in `Description`) to each command. 
-----
Here's an example of the updated CLI output:
```text
NAME:
./sbotcli publish contact - Publish a contact message (follow, unfollow, block, unblock)
USAGE:
./sbotcli publish contact [command options] <@...ed25519>
DESCRIPTION:
Publish a contact message (follow, unfollow, block, unblock).
Example (follow):
sbotcli publish contact --following @r6Lzb9OT3/dlVYNDTABmsF+HWnhBsA1twZaobYhjVUY=.ed25519
Example (unfollow):
sbotcli publish contact @r6Lzb9OT3/dlVYNDTABmsF+HWnhBsA1twZaobYhjVUY=.ed25519
Example (block):
sbotcli publish contact --blocking @r6Lzb9OT3/dlVYNDTABmsF+HWnhBsA1twZaobYhjVUY=.ed25519
Note that both fields (following and blocking) are set with each published contact message.
This means that …
```

Add description fields with example to each command

---

client/client_test.go

I've run this test ~approximately 150~ 116 times, and it has not failed once.  I think whatever was making this fail must have been fixed.  This re-enables the test.
See #237 
Edit: corrected number of test runs.

Re-enable TestStatusCalls test

---

sbot/unipub_test.go

Ran it 100 times, no failures. See https://github.com/ssbc/go-ssb/issues/237.

test: TestPublishUnicode works again

---

plugins/blobs/handler_test.go
sbot/persistence_test.go
tests/local_fork_test.go

Skip more failing tests as we work towards Fixing Them All via https://github.com/ssbc/go-ssb/issues/237.

test: skip TestReplicate & TestStartup

---

sbot/persistence_test.go

Also working just fine after 100 runs, see https://github.com/ssbc/go-ssb/issues/237.

test: TestPersistence works again

---

cmd/gossb-migrate-mf/migrate/migrate_test.go
plugins/gossip/feed_manager.go

Fixes the `TestMigrate` test by detecting the error condition of a closed log and not erroring out at the live feed layer.  Ran successfully 238 times.
Fixes #257 
See also #237

Fix TestMigrate

---

multilogs/indexspeed_test.go
multilogs/integration_prep.bash

Ran successfully 22 times without errors.  This one takes a while to run.
Fixes #279 
See also #237

Fix TestIndexFixtures

---

Makefile
private/box2/spec_test.go

Doesn't actually appear to be broken, as long as you have `envelope-spec` downloaded like the test says.  Hoping the CI system knows how to do that.
Fixes #275 
See also #237

Re-enable TestSpec

---

message/publish_test.go

Related to #289 but does not fix it.
This somewhat cleans up the TestSignMessages test so that it's only testing the publish log externally rather than also relying on the author index directly.  It also tests for a few more things that were previously not tested.  It's not so much a "fix" as a "cleanup" and progress toward narrowing down the issue and testing only what we're looking for so we don't have quite so many disparate functionality failures in a single test.

Clean up TestSignMessages testing methodology

---

sbot/indexes.go
sbot/names_test.go

Requires [https://github.com/ssbc/go-luigi/pull/4](https://github.com/ssbc/go-luigi/pull/4), so be sure to add:
```
replace github.com/ssbc/go-luigi => ./../go-luigi
```
...or something like it to `go.mod` if that pull request hasn't yet been merged.
This fixes #251 and #250 by fixing `idxInSync`, `WaitUntilIndexesAreSynced()`, and `TestNames()`.  I ran `TestNames` over 500 times with zero failures with this in place.

Fix idxInSync, WaitUntilIndexesAreSynced, and TestNames

---

sbot/indexes.go
sbot/new.go

Based on #301 
This adds a function to sbot which allows for querying whether or not the indexes are all up-to-date at the present time.  This could be used for:
- Making sure that publishing during indexing doesn't fork your feed (see #292, #293)
- Status indicator in a UI layer above sbot
- Providing some kind of feedback to a user that if they choose to publish, it will not actually be published until after the indexes finish, depending on how #293 is implemented

Add "are indexes in sync" query

---

plugins2/names/about.go

Fixes #282 
Ran over 3000 times with zero failures.

Fix TestAboutNames

---

message/publish.go
message/publish_test.go
sbot/identities.go
sbot/indexes.go
sbot/new.go

Fixes #293, #292, #289 (ran over 1000 times with no FAILs) and should also fix #250.
So, there's a lot to unpack here:
1. Publishing messages now waits for indexes to finish.  I'd much rather we had some way to query Margaret outside of the indexes and use that so we didn't hold up the caller, but I have not found any way to do that.  This at least fixes a lot of the problems and allows us to move forward with stabilizing things at the cost of convenience for the caller.
2. Indexing now holds the `WaitGroup` for a short time after each message.  This is a theoretically unnecessary delay, but the end effect of this should be to delay publishing of new messages (not appending, because those rely on previous sequence numbers) by about 100 milliseconds.  However, this fixes the problem of the …

Fix multiple index concurrency issues

---

message/publish.go
message/publish_test.go
query/subsetquery_test.go
sbot/identities.go
sbot/indexes.go
sbot/new.go

Ran the test over 1000 times without any `FAIL`s.
Builds off of #308 
Fixes #277

Fix TestSubsetQueryPlanExecution

---

graph/builder.go
graph/builder_indexing.go
graph/builder_test.go

Adds a `WaitGroup` and associated logic so that `BadgerBuilder` queries wait until the indexes have caught up.  This also means we can eliminate the `Sleep()` calls in the test, since it's now based on work being done rather than arbitrary times (other than the short built-in delay to get around Luigi not having a "queue empty" query system).
Fixes #266

Fix TestBadger

---

graph/builder.go
graph/builder_indexing.go
graph/builder_test.go
graph/people_test.go
multilogs/userfeeds.go
sbot/indexes.go
sbot/new.go

Based on #322 
Adds more synchronization to sbot's `WaitUntilIndexesAreSynced()`, which should in general fix a bunch of potential race conditions before they pop up and just generally make indexing more reliable.

Better sync

---

go.mod
go.sum

Following up on https://github.com/ssbc/go-ssb/pull/325.

chore: bump tags for millisecs fix

---

go.mod
go.sum
message/legacy/encode.go
message/legacy/replace.go
message/legacy/replace_test.go
message/legacy/signature.go
message/legacy/verify.go
message/legacy/verify_test.go

This pull request aims to optimize message verification. This is likely to be a hot path in any SSB app and is especially important during initial replication. The speedup visible here won't be directly reflected in the initial replication being proportionally faster in the clients using go-ssb as they will have other overhead as well e.g. the database layer but it should still significantly speed it up. 
Ok this is quite large now but focused on optimizing various functions called from `Verify`. I changed `ExtractSignature` to avoid costly regexp usage and avoid converting bytes to string in `NewSignatureFromBase64`. I replaced `unicodeEscapeSome` function with a faster alternative which attempts to optimize for the common scenario of most characters not
needing escaping and was …

Optimize VerifyWithBuffer

---

message/legacy/encode.go
message/legacy/replace.go
message/legacy/signature.go
message/legacy/verify.go

Environment:
```
goos: linux
goarch: amd64
cpu: AMD Ryzen 7 3700X 8-Core Processor 
```
Results from `master`:
```
BenchmarkVerify-16    	     633	  18817784 ns/op	 5285065 B/op	   23057 allocs/op
```
Results from this pull request:
```
BenchmarkVerify-16    	     694	  16936649 ns/op	 2035855 B/op	   17710 allocs/op
```
This pull request further reduces the execution time to 90% of what it is on `master` and number of allocs to 77% of what it is on `master`.

Further optimizations to VerifyWithBuffer
